[package]
name = "cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "jigc"
path = "src/main.rs"

[dependencies]
engine = { workspace = true }
clap = { workspace = true }
include_dir = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
