[package]
name = "engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
pulldown-cmark.workspace = true
serde.workspace = true
serde_yaml_ng.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
insta = { workspace = true }
proptest = { workspace = true }
